package com.haidela.payment.pay.merchantfail.mapper;

import com.haidela.payment.pay.merchantfail.domain.MerchantFail;

public interface MerchantFailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyx_merchant_fail
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyx_merchant_fail
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    int insert(MerchantFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyx_merchant_fail
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    int insertSelective(MerchantFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyx_merchant_fail
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    MerchantFail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyx_merchant_fail
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    int updateByPrimaryKeySelective(MerchantFail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lyx_merchant_fail
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    int updateByPrimaryKey(MerchantFail record);
}