package com.haidela.payment.pay.merchantfail.domain;

public class MerchantFail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.id
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.merchant_id
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.pay_type
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.amount
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.create_time
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.status
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.tran_flow
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String tranFlow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_merchant_fail.tran_flow_amount
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    private String tranFlowAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.id
     *
     * @return the value of lyx_merchant_fail.id
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.id
     *
     * @param id the value for lyx_merchant_fail.id
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.merchant_id
     *
     * @return the value of lyx_merchant_fail.merchant_id
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.merchant_id
     *
     * @param merchantId the value for lyx_merchant_fail.merchant_id
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.pay_type
     *
     * @return the value of lyx_merchant_fail.pay_type
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.pay_type
     *
     * @param payType the value for lyx_merchant_fail.pay_type
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.amount
     *
     * @return the value of lyx_merchant_fail.amount
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.amount
     *
     * @param amount the value for lyx_merchant_fail.amount
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setAmount(String amount) {
        this.amount = amount == null ? null : amount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.create_time
     *
     * @return the value of lyx_merchant_fail.create_time
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.create_time
     *
     * @param createTime the value for lyx_merchant_fail.create_time
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.status
     *
     * @return the value of lyx_merchant_fail.status
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.status
     *
     * @param status the value for lyx_merchant_fail.status
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.tran_flow
     *
     * @return the value of lyx_merchant_fail.tran_flow
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getTranFlow() {
        return tranFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.tran_flow
     *
     * @param tranFlow the value for lyx_merchant_fail.tran_flow
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setTranFlow(String tranFlow) {
        this.tranFlow = tranFlow == null ? null : tranFlow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_merchant_fail.tran_flow_amount
     *
     * @return the value of lyx_merchant_fail.tran_flow_amount
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public String getTranFlowAmount() {
        return tranFlowAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_merchant_fail.tran_flow_amount
     *
     * @param tranFlowAmount the value for lyx_merchant_fail.tran_flow_amount
     *
     * @mbg.generated Mon Oct 21 19:11:14 CST 2019
     */
    public void setTranFlowAmount(String tranFlowAmount) {
        this.tranFlowAmount = tranFlowAmount == null ? null : tranFlowAmount.trim();
    }
}