package com.haidela.payment.pay.user.domain;

import java.math.BigDecimal;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_user.id
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_user.comp_iD
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    private String compId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_user.company_name
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_user.password
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lyx_user.type
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_user.id
     *
     * @return the value of lyx_user.id
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_user.id
     *
     * @param id the value for lyx_user.id
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_user.comp_iD
     *
     * @return the value of lyx_user.comp_iD
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public String getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_user.comp_iD
     *
     * @param compId the value for lyx_user.comp_iD
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public void setCompId(String compId) {
        this.compId = compId == null ? null : compId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_user.company_name
     *
     * @return the value of lyx_user.company_name
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_user.company_name
     *
     * @param companyName the value for lyx_user.company_name
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_user.password
     *
     * @return the value of lyx_user.password
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_user.password
     *
     * @param password the value for lyx_user.password
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lyx_user.type
     *
     * @return the value of lyx_user.type
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lyx_user.type
     *
     * @param type the value for lyx_user.type
     *
     * @mbg.generated Tue Oct 22 15:46:18 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}